// AUTO-GENERATED by scripts/build-geo.mjs. Do not edit by hand.
// Source geometry: Natural Earth via the world-atlas package (public domain).

export const JOURNEY_VIEWBOX = { width: 1000, height: 560 } as const;
/** Land, France and India outlines, cropped to the map window, as a static image. */
export const JOURNEY_BASE_SRC = "/images/geo/journey-base.svg";
export const JOURNEY_WINDOW = {"x":269,"y":49,"w":395,"h":229} as const;
export const JOURNEY_ARC_PATH = "M513.5,208.9L418.5,176.6";
export const JOURNEY_POINTS = { home: [513.5,208.9], training: [418.5,176.6] } as const;
