// AUTO-GENERATED by scripts/build-geo.mjs. Do not edit by hand.
// Source geometry: Natural Earth via the world-atlas package (public domain).

export const MINI_WORLD_VIEWBOX = { width: 320, height: 160 } as const;
export const MINI_WORLD_SRC = "/images/geo/mini-world.svg";
export const MINI_WORLD_PORTS = {"gorakhpur":[161,56],"varanasi":[161,63],"lucknow":[152,56],"kanpur":[150,57],"prayagraj":[156,62],"ayodhya":[157,56],"kushinagar":[163,56],"gorakhpurAirstrip":[161,56],"lumbini":[160,53],"patna":[169,61],"delhi":[136,47],"agra":[140,54],"dehradun":[137,39],"nainital":[144,44],"ranchi":[171,72],"kathmandu":[168,52]} as const;
