// AUTO-GENERATED by scripts/build-geo.mjs. Do not edit by hand.
// Source geometry: Natural Earth via the world-atlas package (public domain).

export const WORLD_VIEWBOX = { width: 1000, height: 470 } as const;
/** Land outline lives in /public/images/geo/world-land.svg (loaded lazily as an image). */
export const WORLD_LAND_SRC = "/images/geo/world-land.svg";
export const WORLD_PORTS = {"gorakhpur":[503.4,164.4],"varanasi":[502.4,184.2],"lucknow":[475.5,163.2],"kanpur":[469.5,168.6],"prayagraj":[489.2,182.5],"ayodhya":[489.9,163.9],"kushinagar":[509.5,164.6],"gorakhpurAirstrip":[504.3,164.7],"lumbini":[500.4,154.4],"patna":[526.4,180.4],"delhi":[428.7,138.9],"agra":[441.3,158.7],"dehradun":[433.5,115.5],"nainital":[452.1,128.2],"ranchi":[533.7,211.2],"kathmandu":[523,151.2]} as const;
export type HubId = keyof typeof WORLD_PORTS;
